"""initial

Revision ID: 947466f828bd
Revises: 
Create Date: 2026-03-10 14:08:06.998160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947466f828bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lenders_id'), 'lenders', ['id'], unique=False)
    op.create_index(op.f('ix_lenders_slug'), 'lenders', ['slug'], unique=True)
    op.create_table('loan_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('years_in_business', sa.Float(), nullable=True),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('fico_score', sa.Integer(), nullable=True),
    sa.Column('paynet_score', sa.Integer(), nullable=True),
    sa.Column('transunion_score', sa.Integer(), nullable=True),
    sa.Column('loan_amount', sa.Float(), nullable=True),
    sa.Column('equipment_type', sa.String(length=100), nullable=True),
    sa.Column('equipment_year', sa.Integer(), nullable=True),
    sa.Column('equipment_mileage', sa.Integer(), nullable=True),
    sa.Column('is_startup', sa.Boolean(), nullable=False),
    sa.Column('has_bankruptcy', sa.Boolean(), nullable=False),
    sa.Column('bankruptcy_years_ago', sa.Float(), nullable=True),
    sa.Column('has_judgments', sa.Boolean(), nullable=False),
    sa.Column('has_repossessions', sa.Boolean(), nullable=False),
    sa.Column('has_tax_liens', sa.Boolean(), nullable=False),
    sa.Column('is_us_citizen', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'complete', name='application_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_id'), 'loan_applications', ['id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_index(op.f('ix_programs_lender_id'), 'programs', ['lender_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_application_id'), 'match_results', ['application_id'], unique=False)
    op.create_index(op.f('ix_match_results_id'), 'match_results', ['id'], unique=False)
    op.create_index(op.f('ix_match_results_lender_id'), 'match_results', ['lender_id'], unique=False)
    op.create_index(op.f('ix_match_results_program_id'), 'match_results', ['program_id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.Enum('gte', 'lte', 'gt', 'lt', 'equals', 'not_in', 'in_', name='rule_operator'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_hard_stop', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_id'), 'policy_rules', ['id'], unique=False)
    op.create_index(op.f('ix_policy_rules_program_id'), 'policy_rules', ['program_id'], unique=False)
    op.create_table('rule_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_result_id', sa.Integer(), nullable=False),
    sa.Column('policy_rule_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('required_value', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ),
    sa.ForeignKeyConstraint(['policy_rule_id'], ['policy_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_evaluations_id'), 'rule_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_rule_evaluations_match_result_id'), 'rule_evaluations', ['match_result_id'], unique=False)
    op.create_index(op.f('ix_rule_evaluations_policy_rule_id'), 'rule_evaluations', ['policy_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_evaluations_policy_rule_id'), table_name='rule_evaluations')
    op.drop_index(op.f('ix_rule_evaluations_match_result_id'), table_name='rule_evaluations')
    op.drop_index(op.f('ix_rule_evaluations_id'), table_name='rule_evaluations')
    op.drop_table('rule_evaluations')
    op.drop_index(op.f('ix_policy_rules_program_id'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_match_results_program_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_lender_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_application_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_programs_lender_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_loan_applications_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_lenders_slug'), table_name='lenders')
    op.drop_index(op.f('ix_lenders_id'), table_name='lenders')
    op.drop_table('lenders')
    # ### end Alembic commands ###